/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * NamedResourcesStringSlice contains a slice of strings.
 * @export
 * @interface V1alpha2NamedResourcesStringSlice
 */
export interface V1alpha2NamedResourcesStringSlice {
    /**
     * Strings is the slice of strings.
     * @type {Array<string>}
     * @memberof V1alpha2NamedResourcesStringSlice
     */
    strings: Array<string>;
}

/**
 * Check if a given object implements the V1alpha2NamedResourcesStringSlice interface.
 */
export function instanceOfV1alpha2NamedResourcesStringSlice(value: object): value is V1alpha2NamedResourcesStringSlice {
    if (!('strings' in value) || value['strings'] === undefined) return false;
    return true;
}

export function V1alpha2NamedResourcesStringSliceFromJSON(json: any): V1alpha2NamedResourcesStringSlice {
    return V1alpha2NamedResourcesStringSliceFromJSONTyped(json, false);
}

export function V1alpha2NamedResourcesStringSliceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1alpha2NamedResourcesStringSlice {
    if (json == null) {
        return json;
    }
    return {
        
        'strings': json['strings'],
    };
}

export function V1alpha2NamedResourcesStringSliceToJSON(value?: V1alpha2NamedResourcesStringSlice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'strings': value['strings'],
    };
}

