/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1GroupVersionForDiscovery } from './V1GroupVersionForDiscovery';
import {
    V1GroupVersionForDiscoveryFromJSON,
    V1GroupVersionForDiscoveryFromJSONTyped,
    V1GroupVersionForDiscoveryToJSON,
} from './V1GroupVersionForDiscovery';
import type { V1ServerAddressByClientCIDR } from './V1ServerAddressByClientCIDR';
import {
    V1ServerAddressByClientCIDRFromJSON,
    V1ServerAddressByClientCIDRFromJSONTyped,
    V1ServerAddressByClientCIDRToJSON,
} from './V1ServerAddressByClientCIDR';

/**
 * APIGroup contains the name, the supported versions, and the preferred version of a group.
 * @export
 * @interface V1APIGroup
 */
export interface V1APIGroup {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1APIGroup
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1APIGroup
     */
    kind?: string;
    /**
     * name is the name of the group.
     * @type {string}
     * @memberof V1APIGroup
     */
    name: string;
    /**
     * 
     * @type {V1GroupVersionForDiscovery}
     * @memberof V1APIGroup
     */
    preferredVersion?: V1GroupVersionForDiscovery;
    /**
     * a map of client CIDR to server address that is serving this group. This is to help clients reach servers in the most network-efficient way possible. Clients can use the appropriate server address as per the CIDR that they match. In case of multiple matches, clients should use the longest matching CIDR. The server returns only those CIDRs that it thinks that the client can match. For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP. Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
     * @type {Array<V1ServerAddressByClientCIDR>}
     * @memberof V1APIGroup
     */
    serverAddressByClientCIDRs?: Array<V1ServerAddressByClientCIDR>;
    /**
     * versions are the versions supported in this group.
     * @type {Array<V1GroupVersionForDiscovery>}
     * @memberof V1APIGroup
     */
    versions: Array<V1GroupVersionForDiscovery>;
}

/**
 * Check if a given object implements the V1APIGroup interface.
 */
export function instanceOfV1APIGroup(value: object): value is V1APIGroup {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function V1APIGroupFromJSON(json: any): V1APIGroup {
    return V1APIGroupFromJSONTyped(json, false);
}

export function V1APIGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1APIGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'name': json['name'],
        'preferredVersion': json['preferredVersion'] == null ? undefined : V1GroupVersionForDiscoveryFromJSON(json['preferredVersion']),
        'serverAddressByClientCIDRs': json['serverAddressByClientCIDRs'] == null ? undefined : ((json['serverAddressByClientCIDRs'] as Array<any>).map(V1ServerAddressByClientCIDRFromJSON)),
        'versions': ((json['versions'] as Array<any>).map(V1GroupVersionForDiscoveryFromJSON)),
    };
}

export function V1APIGroupToJSON(value?: V1APIGroup | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'name': value['name'],
        'preferredVersion': V1GroupVersionForDiscoveryToJSON(value['preferredVersion']),
        'serverAddressByClientCIDRs': value['serverAddressByClientCIDRs'] == null ? undefined : ((value['serverAddressByClientCIDRs'] as Array<any>).map(V1ServerAddressByClientCIDRToJSON)),
        'versions': ((value['versions'] as Array<any>).map(V1GroupVersionForDiscoveryToJSON)),
    };
}

