/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.24.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * PriorityLevelConfigurationReference contains information that points to the "request-priority" being used.
 * @export
 * @interface V1beta2PriorityLevelConfigurationReference
 */
export interface V1beta2PriorityLevelConfigurationReference {
    /**
     * `name` is the name of the priority level configuration being referenced Required.
     * @type {string}
     * @memberof V1beta2PriorityLevelConfigurationReference
     */
    name: string;
}

/**
 * Check if a given object implements the V1beta2PriorityLevelConfigurationReference interface.
 */
export function instanceOfV1beta2PriorityLevelConfigurationReference(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function V1beta2PriorityLevelConfigurationReferenceFromJSON(json: any): V1beta2PriorityLevelConfigurationReference {
    return V1beta2PriorityLevelConfigurationReferenceFromJSONTyped(json, false);
}

export function V1beta2PriorityLevelConfigurationReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta2PriorityLevelConfigurationReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function V1beta2PriorityLevelConfigurationReferenceToJSON(value?: V1beta2PriorityLevelConfigurationReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

