/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.28.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * PriorityLevelConfigurationCondition defines the condition of priority level.
 * @export
 * @interface V1beta2PriorityLevelConfigurationCondition
 */
export interface V1beta2PriorityLevelConfigurationCondition {
    /**
     * `lastTransitionTime` is the last time the condition transitioned from one status to another.
     * @type {Date}
     * @memberof V1beta2PriorityLevelConfigurationCondition
     */
    lastTransitionTime?: Date;
    /**
     * `message` is a human-readable message indicating details about last transition.
     * @type {string}
     * @memberof V1beta2PriorityLevelConfigurationCondition
     */
    message?: string;
    /**
     * `reason` is a unique, one-word, CamelCase reason for the condition's last transition.
     * @type {string}
     * @memberof V1beta2PriorityLevelConfigurationCondition
     */
    reason?: string;
    /**
     * `status` is the status of the condition. Can be True, False, Unknown. Required.
     * @type {string}
     * @memberof V1beta2PriorityLevelConfigurationCondition
     */
    status?: string;
    /**
     * `type` is the type of the condition. Required.
     * @type {string}
     * @memberof V1beta2PriorityLevelConfigurationCondition
     */
    type?: string;
}

/**
 * Check if a given object implements the V1beta2PriorityLevelConfigurationCondition interface.
 */
export function instanceOfV1beta2PriorityLevelConfigurationCondition(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1beta2PriorityLevelConfigurationConditionFromJSON(json: any): V1beta2PriorityLevelConfigurationCondition {
    return V1beta2PriorityLevelConfigurationConditionFromJSONTyped(json, false);
}

export function V1beta2PriorityLevelConfigurationConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta2PriorityLevelConfigurationCondition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastTransitionTime': !exists(json, 'lastTransitionTime') ? undefined : (new Date(json['lastTransitionTime'])),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function V1beta2PriorityLevelConfigurationConditionToJSON(value?: V1beta2PriorityLevelConfigurationCondition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastTransitionTime': value.lastTransitionTime === undefined ? undefined : (value.lastTransitionTime.toISOString()),
        'message': value.message,
        'reason': value.reason,
        'status': value.status,
        'type': value.type,
    };
}

