/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.24.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Overhead structure represents the resource overhead associated with running a pod.
 * @export
 * @interface V1beta1Overhead
 */
export interface V1beta1Overhead {
    /**
     * PodFixed represents the fixed resource overhead associated with running a pod.
     * @type {{ [key: string]: string; }}
     * @memberof V1beta1Overhead
     */
    podFixed?: { [key: string]: string; };
}

/**
 * Check if a given object implements the V1beta1Overhead interface.
 */
export function instanceOfV1beta1Overhead(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1beta1OverheadFromJSON(json: any): V1beta1Overhead {
    return V1beta1OverheadFromJSONTyped(json, false);
}

export function V1beta1OverheadFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1Overhead {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'podFixed': !exists(json, 'podFixed') ? undefined : json['podFixed'],
    };
}

export function V1beta1OverheadToJSON(value?: V1beta1Overhead | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'podFixed': value.podFixed,
    };
}

