/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.24.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ForZone provides information about which zones should consume this endpoint.
 * @export
 * @interface V1beta1ForZone
 */
export interface V1beta1ForZone {
    /**
     * name represents the name of the zone.
     * @type {string}
     * @memberof V1beta1ForZone
     */
    name: string;
}

/**
 * Check if a given object implements the V1beta1ForZone interface.
 */
export function instanceOfV1beta1ForZone(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function V1beta1ForZoneFromJSON(json: any): V1beta1ForZone {
    return V1beta1ForZoneFromJSONTyped(json, false);
}

export function V1beta1ForZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1ForZone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function V1beta1ForZoneToJSON(value?: V1beta1ForZone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

