/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.24.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1beta2QueuingConfiguration } from './V1beta2QueuingConfiguration';
import {
    V1beta2QueuingConfigurationFromJSON,
    V1beta2QueuingConfigurationFromJSONTyped,
    V1beta2QueuingConfigurationToJSON,
} from './V1beta2QueuingConfiguration';

/**
 * LimitResponse defines how to handle requests that can not be executed right now.
 * @export
 * @interface V1beta2LimitResponse
 */
export interface V1beta2LimitResponse {
    /**
     * 
     * @type {V1beta2QueuingConfiguration}
     * @memberof V1beta2LimitResponse
     */
    queuing?: V1beta2QueuingConfiguration;
    /**
     * `type` is "Queue" or "Reject". "Queue" means that requests that can not be executed upon arrival are held in a queue until they can be executed or a queuing limit is reached. "Reject" means that requests that can not be executed upon arrival are rejected. Required.
     * @type {string}
     * @memberof V1beta2LimitResponse
     */
    type: string;
}

/**
 * Check if a given object implements the V1beta2LimitResponse interface.
 */
export function instanceOfV1beta2LimitResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function V1beta2LimitResponseFromJSON(json: any): V1beta2LimitResponse {
    return V1beta2LimitResponseFromJSONTyped(json, false);
}

export function V1beta2LimitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta2LimitResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queuing': !exists(json, 'queuing') ? undefined : V1beta2QueuingConfigurationFromJSON(json['queuing']),
        'type': json['type'],
    };
}

export function V1beta2LimitResponseToJSON(value?: V1beta2LimitResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'queuing': V1beta2QueuingConfigurationToJSON(value.queuing),
        'type': value.type,
    };
}

