/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.24.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
 * @export
 * @interface V1beta1EventSeries
 */
export interface V1beta1EventSeries {
    /**
     * count is the number of occurrences in this series up to the last heartbeat time.
     * @type {number}
     * @memberof V1beta1EventSeries
     */
    count: number;
    /**
     * lastObservedTime is the time when last Event from the series was seen before last heartbeat.
     * @type {Date}
     * @memberof V1beta1EventSeries
     */
    lastObservedTime: Date;
}

/**
 * Check if a given object implements the V1beta1EventSeries interface.
 */
export function instanceOfV1beta1EventSeries(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "lastObservedTime" in value;

    return isInstance;
}

export function V1beta1EventSeriesFromJSON(json: any): V1beta1EventSeries {
    return V1beta1EventSeriesFromJSONTyped(json, false);
}

export function V1beta1EventSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1EventSeries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'lastObservedTime': (new Date(json['lastObservedTime'])),
    };
}

export function V1beta1EventSeriesToJSON(value?: V1beta1EventSeries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'lastObservedTime': (value.lastObservedTime.toISOString()),
    };
}

