/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1beta1AuditAnnotation } from './V1beta1AuditAnnotation';
import {
    V1beta1AuditAnnotationFromJSON,
    V1beta1AuditAnnotationFromJSONTyped,
    V1beta1AuditAnnotationToJSON,
} from './V1beta1AuditAnnotation';
import type { V1beta1MatchCondition } from './V1beta1MatchCondition';
import {
    V1beta1MatchConditionFromJSON,
    V1beta1MatchConditionFromJSONTyped,
    V1beta1MatchConditionToJSON,
} from './V1beta1MatchCondition';
import type { V1beta1Validation } from './V1beta1Validation';
import {
    V1beta1ValidationFromJSON,
    V1beta1ValidationFromJSONTyped,
    V1beta1ValidationToJSON,
} from './V1beta1Validation';
import type { V1beta1MatchResources } from './V1beta1MatchResources';
import {
    V1beta1MatchResourcesFromJSON,
    V1beta1MatchResourcesFromJSONTyped,
    V1beta1MatchResourcesToJSON,
} from './V1beta1MatchResources';
import type { V1beta1Variable } from './V1beta1Variable';
import {
    V1beta1VariableFromJSON,
    V1beta1VariableFromJSONTyped,
    V1beta1VariableToJSON,
} from './V1beta1Variable';
import type { V1beta1ParamKind } from './V1beta1ParamKind';
import {
    V1beta1ParamKindFromJSON,
    V1beta1ParamKindFromJSONTyped,
    V1beta1ParamKindToJSON,
} from './V1beta1ParamKind';

/**
 * ValidatingAdmissionPolicySpec is the specification of the desired behavior of the AdmissionPolicy.
 * @export
 * @interface V1beta1ValidatingAdmissionPolicySpec
 */
export interface V1beta1ValidatingAdmissionPolicySpec {
    /**
     * auditAnnotations contains CEL expressions which are used to produce audit annotations for the audit event of the API request. validations and auditAnnotations may not both be empty; a least one of validations or auditAnnotations is required.
     * @type {Array<V1beta1AuditAnnotation>}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    auditAnnotations?: Array<V1beta1AuditAnnotation>;
    /**
     * failurePolicy defines how to handle failures for the admission policy. Failures can occur from CEL expression parse errors, type check errors, runtime errors and invalid or mis-configured policy definitions or bindings.
     * 
     * A policy is invalid if spec.paramKind refers to a non-existent Kind. A binding is invalid if spec.paramRef.name refers to a non-existent resource.
     * 
     * failurePolicy does not define how validations that evaluate to false are handled.
     * 
     * When failurePolicy is set to Fail, ValidatingAdmissionPolicyBinding validationActions define how failures are enforced.
     * 
     * Allowed values are Ignore or Fail. Defaults to Fail.
     * @type {string}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    failurePolicy?: string;
    /**
     * MatchConditions is a list of conditions that must be met for a request to be validated. Match conditions filter requests that have already been matched by the rules, namespaceSelector, and objectSelector. An empty list of matchConditions matches all requests. There are a maximum of 64 match conditions allowed.
     * 
     * If a parameter object is provided, it can be accessed via the `params` handle in the same manner as validation expressions.
     * 
     * The exact matching logic is (in order):
     *   1. If ANY matchCondition evaluates to FALSE, the policy is skipped.
     *   2. If ALL matchConditions evaluate to TRUE, the policy is evaluated.
     *   3. If any matchCondition evaluates to an error (but none are FALSE):
     *      - If failurePolicy=Fail, reject the request
     *      - If failurePolicy=Ignore, the policy is skipped
     * @type {Array<V1beta1MatchCondition>}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    matchConditions?: Array<V1beta1MatchCondition>;
    /**
     * 
     * @type {V1beta1MatchResources}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    matchConstraints?: V1beta1MatchResources;
    /**
     * 
     * @type {V1beta1ParamKind}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    paramKind?: V1beta1ParamKind;
    /**
     * Validations contain CEL expressions which is used to apply the validation. Validations and AuditAnnotations may not both be empty; a minimum of one Validations or AuditAnnotations is required.
     * @type {Array<V1beta1Validation>}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    validations?: Array<V1beta1Validation>;
    /**
     * Variables contain definitions of variables that can be used in composition of other expressions. Each variable is defined as a named CEL expression. The variables defined here will be available under `variables` in other expressions of the policy except MatchConditions because MatchConditions are evaluated before the rest of the policy.
     * 
     * The expression of a variable can refer to other variables defined earlier in the list but not those after. Thus, Variables must be sorted by the order of first appearance and acyclic.
     * @type {Array<V1beta1Variable>}
     * @memberof V1beta1ValidatingAdmissionPolicySpec
     */
    variables?: Array<V1beta1Variable>;
}

/**
 * Check if a given object implements the V1beta1ValidatingAdmissionPolicySpec interface.
 */
export function instanceOfV1beta1ValidatingAdmissionPolicySpec(value: object): value is V1beta1ValidatingAdmissionPolicySpec {
    return true;
}

export function V1beta1ValidatingAdmissionPolicySpecFromJSON(json: any): V1beta1ValidatingAdmissionPolicySpec {
    return V1beta1ValidatingAdmissionPolicySpecFromJSONTyped(json, false);
}

export function V1beta1ValidatingAdmissionPolicySpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1ValidatingAdmissionPolicySpec {
    if (json == null) {
        return json;
    }
    return {
        
        'auditAnnotations': json['auditAnnotations'] == null ? undefined : ((json['auditAnnotations'] as Array<any>).map(V1beta1AuditAnnotationFromJSON)),
        'failurePolicy': json['failurePolicy'] == null ? undefined : json['failurePolicy'],
        'matchConditions': json['matchConditions'] == null ? undefined : ((json['matchConditions'] as Array<any>).map(V1beta1MatchConditionFromJSON)),
        'matchConstraints': json['matchConstraints'] == null ? undefined : V1beta1MatchResourcesFromJSON(json['matchConstraints']),
        'paramKind': json['paramKind'] == null ? undefined : V1beta1ParamKindFromJSON(json['paramKind']),
        'validations': json['validations'] == null ? undefined : ((json['validations'] as Array<any>).map(V1beta1ValidationFromJSON)),
        'variables': json['variables'] == null ? undefined : ((json['variables'] as Array<any>).map(V1beta1VariableFromJSON)),
    };
}

export function V1beta1ValidatingAdmissionPolicySpecToJSON(value?: V1beta1ValidatingAdmissionPolicySpec | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'auditAnnotations': value['auditAnnotations'] == null ? undefined : ((value['auditAnnotations'] as Array<any>).map(V1beta1AuditAnnotationToJSON)),
        'failurePolicy': value['failurePolicy'],
        'matchConditions': value['matchConditions'] == null ? undefined : ((value['matchConditions'] as Array<any>).map(V1beta1MatchConditionToJSON)),
        'matchConstraints': V1beta1MatchResourcesToJSON(value['matchConstraints']),
        'paramKind': V1beta1ParamKindToJSON(value['paramKind']),
        'validations': value['validations'] == null ? undefined : ((value['validations'] as Array<any>).map(V1beta1ValidationToJSON)),
        'variables': value['variables'] == null ? undefined : ((value['variables'] as Array<any>).map(V1beta1VariableToJSON)),
    };
}

