/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.24
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AllowedFlexVolume represents a single Flexvolume that is allowed to be used.
 * @export
 * @interface V1beta1AllowedFlexVolume
 */
export interface V1beta1AllowedFlexVolume {
    /**
     * driver is the name of the Flexvolume driver.
     * @type {string}
     * @memberof V1beta1AllowedFlexVolume
     */
    driver: string;
}

export function V1beta1AllowedFlexVolumeFromJSON(json: any): V1beta1AllowedFlexVolume {
    return V1beta1AllowedFlexVolumeFromJSONTyped(json, false);
}

export function V1beta1AllowedFlexVolumeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1AllowedFlexVolume {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'driver': json['driver'],
    };
}

export function V1beta1AllowedFlexVolumeToJSON(value?: V1beta1AllowedFlexVolume | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'driver': value.driver,
    };
}


