/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ClaimSource describes a reference to a ResourceClaim.
 * 
 * Exactly one of these fields should be set.  Consumers of this type must treat an empty object as if it has an unknown value.
 * @export
 * @interface V1ClaimSource
 */
export interface V1ClaimSource {
    /**
     * ResourceClaimName is the name of a ResourceClaim object in the same namespace as this pod.
     * @type {string}
     * @memberof V1ClaimSource
     */
    resourceClaimName?: string;
    /**
     * ResourceClaimTemplateName is the name of a ResourceClaimTemplate object in the same namespace as this pod.
     * 
     * The template will be used to create a new ResourceClaim, which will be bound to this pod. When this pod is deleted, the ResourceClaim will also be deleted. The pod name and resource name, along with a generated component, will be used to form a unique name for the ResourceClaim, which will be recorded in pod.status.resourceClaimStatuses.
     * 
     * This field is immutable and no changes will be made to the corresponding ResourceClaim by the control plane after creating the ResourceClaim.
     * @type {string}
     * @memberof V1ClaimSource
     */
    resourceClaimTemplateName?: string;
}

/**
 * Check if a given object implements the V1ClaimSource interface.
 */
export function instanceOfV1ClaimSource(value: object): value is V1ClaimSource {
    return true;
}

export function V1ClaimSourceFromJSON(json: any): V1ClaimSource {
    return V1ClaimSourceFromJSONTyped(json, false);
}

export function V1ClaimSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClaimSource {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceClaimName': json['resourceClaimName'] == null ? undefined : json['resourceClaimName'],
        'resourceClaimTemplateName': json['resourceClaimTemplateName'] == null ? undefined : json['resourceClaimTemplateName'],
    };
}

export function V1ClaimSourceToJSON(value?: V1ClaimSource | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'resourceClaimName': value['resourceClaimName'],
        'resourceClaimTemplateName': value['resourceClaimTemplateName'],
    };
}

