/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.24
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1CSIStorageCapacity,
    V1CSIStorageCapacityFromJSON,
    V1CSIStorageCapacityFromJSONTyped,
    V1CSIStorageCapacityToJSON,
    V1ListMeta,
    V1ListMetaFromJSON,
    V1ListMetaFromJSONTyped,
    V1ListMetaToJSON,
} from './';

/**
 * CSIStorageCapacityList is a collection of CSIStorageCapacity objects.
 * @export
 * @interface V1CSIStorageCapacityList
 */
export interface V1CSIStorageCapacityList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1CSIStorageCapacityList
     */
    apiVersion?: string;
    /**
     * Items is the list of CSIStorageCapacity objects.
     * @type {Array<V1CSIStorageCapacity>}
     * @memberof V1CSIStorageCapacityList
     */
    items: Array<V1CSIStorageCapacity>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1CSIStorageCapacityList
     */
    kind?: string;
    /**
     * 
     * @type {V1ListMeta}
     * @memberof V1CSIStorageCapacityList
     */
    metadata?: V1ListMeta;
}

export function V1CSIStorageCapacityListFromJSON(json: any): V1CSIStorageCapacityList {
    return V1CSIStorageCapacityListFromJSONTyped(json, false);
}

export function V1CSIStorageCapacityListFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CSIStorageCapacityList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'items': ((json['items'] as Array<any>).map(V1CSIStorageCapacityFromJSON)),
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : V1ListMetaFromJSON(json['metadata']),
    };
}

export function V1CSIStorageCapacityListToJSON(value?: V1CSIStorageCapacityList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'items': ((value.items as Array<any>).map(V1CSIStorageCapacityToJSON)),
        'kind': value.kind,
        'metadata': V1ListMetaToJSON(value.metadata),
    };
}


