/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.24.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1RollingUpdateDeployment } from './V1RollingUpdateDeployment';
import {
    V1RollingUpdateDeploymentFromJSON,
    V1RollingUpdateDeploymentFromJSONTyped,
    V1RollingUpdateDeploymentToJSON,
} from './V1RollingUpdateDeployment';

/**
 * DeploymentStrategy describes how to replace existing pods with new ones.
 * @export
 * @interface V1DeploymentStrategy
 */
export interface V1DeploymentStrategy {
    /**
     * 
     * @type {V1RollingUpdateDeployment}
     * @memberof V1DeploymentStrategy
     */
    rollingUpdate?: V1RollingUpdateDeployment;
    /**
     * Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
     * @type {string}
     * @memberof V1DeploymentStrategy
     */
    type?: string;
}

/**
 * Check if a given object implements the V1DeploymentStrategy interface.
 */
export function instanceOfV1DeploymentStrategy(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1DeploymentStrategyFromJSON(json: any): V1DeploymentStrategy {
    return V1DeploymentStrategyFromJSONTyped(json, false);
}

export function V1DeploymentStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeploymentStrategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rollingUpdate': !exists(json, 'rollingUpdate') ? undefined : V1RollingUpdateDeploymentFromJSON(json['rollingUpdate']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function V1DeploymentStrategyToJSON(value?: V1DeploymentStrategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rollingUpdate': V1RollingUpdateDeploymentToJSON(value.rollingUpdate),
        'type': value.type,
    };
}

