/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.24
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ForZone provides information about which zones should consume this endpoint.
 * @export
 * @interface V1ForZone
 */
export interface V1ForZone {
    /**
     * name represents the name of the zone.
     * @type {string}
     * @memberof V1ForZone
     */
    name: string;
}

export function V1ForZoneFromJSON(json: any): V1ForZone {
    return V1ForZoneFromJSONTyped(json, false);
}

export function V1ForZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ForZone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function V1ForZoneToJSON(value?: V1ForZone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


