/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 * @export
 * @interface V1HTTPHeader
 */
export interface V1HTTPHeader {
    /**
     * The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
     * @type {string}
     * @memberof V1HTTPHeader
     */
    name: string;
    /**
     * The header field value
     * @type {string}
     * @memberof V1HTTPHeader
     */
    value: string;
}

/**
 * Check if a given object implements the V1HTTPHeader interface.
 */
export function instanceOfV1HTTPHeader(value: object): value is V1HTTPHeader {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function V1HTTPHeaderFromJSON(json: any): V1HTTPHeader {
    return V1HTTPHeaderFromJSONTyped(json, false);
}

export function V1HTTPHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1HTTPHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function V1HTTPHeaderToJSON(value?: V1HTTPHeader | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

