/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.28.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1IngressLoadBalancerStatus } from './V1IngressLoadBalancerStatus';
import {
    V1IngressLoadBalancerStatusFromJSON,
    V1IngressLoadBalancerStatusFromJSONTyped,
    V1IngressLoadBalancerStatusToJSON,
} from './V1IngressLoadBalancerStatus';

/**
 * IngressStatus describe the current state of the Ingress.
 * @export
 * @interface V1IngressStatus
 */
export interface V1IngressStatus {
    /**
     * 
     * @type {V1IngressLoadBalancerStatus}
     * @memberof V1IngressStatus
     */
    loadBalancer?: V1IngressLoadBalancerStatus;
}

/**
 * Check if a given object implements the V1IngressStatus interface.
 */
export function instanceOfV1IngressStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1IngressStatusFromJSON(json: any): V1IngressStatus {
    return V1IngressStatusFromJSONTyped(json, false);
}

export function V1IngressStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IngressStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loadBalancer': !exists(json, 'loadBalancer') ? undefined : V1IngressLoadBalancerStatusFromJSON(json['loadBalancer']),
    };
}

export function V1IngressStatusToJSON(value?: V1IngressStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'loadBalancer': V1IngressLoadBalancerStatusToJSON(value.loadBalancer),
    };
}

