/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1LifecycleHandler } from './V1LifecycleHandler';
import {
    V1LifecycleHandlerFromJSON,
    V1LifecycleHandlerFromJSONTyped,
    V1LifecycleHandlerToJSON,
} from './V1LifecycleHandler';

/**
 * Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.
 * @export
 * @interface V1Lifecycle
 */
export interface V1Lifecycle {
    /**
     * 
     * @type {V1LifecycleHandler}
     * @memberof V1Lifecycle
     */
    postStart?: V1LifecycleHandler;
    /**
     * 
     * @type {V1LifecycleHandler}
     * @memberof V1Lifecycle
     */
    preStop?: V1LifecycleHandler;
}

/**
 * Check if a given object implements the V1Lifecycle interface.
 */
export function instanceOfV1Lifecycle(value: object): value is V1Lifecycle {
    return true;
}

export function V1LifecycleFromJSON(json: any): V1Lifecycle {
    return V1LifecycleFromJSONTyped(json, false);
}

export function V1LifecycleFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Lifecycle {
    if (json == null) {
        return json;
    }
    return {
        
        'postStart': json['postStart'] == null ? undefined : V1LifecycleHandlerFromJSON(json['postStart']),
        'preStop': json['preStop'] == null ? undefined : V1LifecycleHandlerFromJSON(json['preStop']),
    };
}

export function V1LifecycleToJSON(value?: V1Lifecycle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'postStart': V1LifecycleHandlerToJSON(value['postStart']),
        'preStop': V1LifecycleHandlerToJSON(value['preStop']),
    };
}

