/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ModifyVolumeStatus represents the status object of ControllerModifyVolume operation
 * @export
 * @interface V1ModifyVolumeStatus
 */
export interface V1ModifyVolumeStatus {
    /**
     * status is the status of the ControllerModifyVolume operation. It can be in any of following states:
     *  - Pending
     *    Pending indicates that the PersistentVolumeClaim cannot be modified due to unmet requirements, such as
     *    the specified VolumeAttributesClass not existing.
     *  - InProgress
     *    InProgress indicates that the volume is being modified.
     *  - Infeasible
     *   Infeasible indicates that the request has been rejected as invalid by the CSI driver. To
     * 	  resolve the error, a valid VolumeAttributesClass needs to be specified.
     * Note: New statuses can be added in the future. Consumers should check for unknown statuses and fail appropriately.
     * @type {string}
     * @memberof V1ModifyVolumeStatus
     */
    status: string;
    /**
     * targetVolumeAttributesClassName is the name of the VolumeAttributesClass the PVC currently being reconciled
     * @type {string}
     * @memberof V1ModifyVolumeStatus
     */
    targetVolumeAttributesClassName?: string;
}

/**
 * Check if a given object implements the V1ModifyVolumeStatus interface.
 */
export function instanceOfV1ModifyVolumeStatus(value: object): value is V1ModifyVolumeStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function V1ModifyVolumeStatusFromJSON(json: any): V1ModifyVolumeStatus {
    return V1ModifyVolumeStatusFromJSONTyped(json, false);
}

export function V1ModifyVolumeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ModifyVolumeStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'targetVolumeAttributesClassName': json['targetVolumeAttributesClassName'] == null ? undefined : json['targetVolumeAttributesClassName'],
    };
}

export function V1ModifyVolumeStatusToJSON(value?: V1ModifyVolumeStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'targetVolumeAttributesClassName': value['targetVolumeAttributesClassName'],
    };
}

