/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1MutatingWebhookConfiguration } from './V1MutatingWebhookConfiguration';
import {
    V1MutatingWebhookConfigurationFromJSON,
    V1MutatingWebhookConfigurationFromJSONTyped,
    V1MutatingWebhookConfigurationToJSON,
} from './V1MutatingWebhookConfiguration';
import type { V1ListMeta } from './V1ListMeta';
import {
    V1ListMetaFromJSON,
    V1ListMetaFromJSONTyped,
    V1ListMetaToJSON,
} from './V1ListMeta';

/**
 * MutatingWebhookConfigurationList is a list of MutatingWebhookConfiguration.
 * @export
 * @interface V1MutatingWebhookConfigurationList
 */
export interface V1MutatingWebhookConfigurationList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1MutatingWebhookConfigurationList
     */
    apiVersion?: string;
    /**
     * List of MutatingWebhookConfiguration.
     * @type {Array<V1MutatingWebhookConfiguration>}
     * @memberof V1MutatingWebhookConfigurationList
     */
    items: Array<V1MutatingWebhookConfiguration>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1MutatingWebhookConfigurationList
     */
    kind?: string;
    /**
     * 
     * @type {V1ListMeta}
     * @memberof V1MutatingWebhookConfigurationList
     */
    metadata?: V1ListMeta;
}

/**
 * Check if a given object implements the V1MutatingWebhookConfigurationList interface.
 */
export function instanceOfV1MutatingWebhookConfigurationList(value: object): value is V1MutatingWebhookConfigurationList {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function V1MutatingWebhookConfigurationListFromJSON(json: any): V1MutatingWebhookConfigurationList {
    return V1MutatingWebhookConfigurationListFromJSONTyped(json, false);
}

export function V1MutatingWebhookConfigurationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1MutatingWebhookConfigurationList {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'items': ((json['items'] as Array<any>).map(V1MutatingWebhookConfigurationFromJSON)),
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : V1ListMetaFromJSON(json['metadata']),
    };
}

export function V1MutatingWebhookConfigurationListToJSON(value?: V1MutatingWebhookConfigurationList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiVersion': value['apiVersion'],
        'items': ((value['items'] as Array<any>).map(V1MutatingWebhookConfigurationToJSON)),
        'kind': value['kind'],
        'metadata': V1ListMetaToJSON(value['metadata']),
    };
}

