/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1NodeStatus } from './V1NodeStatus';
import {
    V1NodeStatusFromJSON,
    V1NodeStatusFromJSONTyped,
    V1NodeStatusToJSON,
} from './V1NodeStatus';
import type { V1ObjectMeta } from './V1ObjectMeta';
import {
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
} from './V1ObjectMeta';
import type { V1NodeSpec } from './V1NodeSpec';
import {
    V1NodeSpecFromJSON,
    V1NodeSpecFromJSONTyped,
    V1NodeSpecToJSON,
} from './V1NodeSpec';

/**
 * Node is a worker node in Kubernetes. Each node will have a unique identifier in the cache (i.e. in etcd).
 * @export
 * @interface V1Node
 */
export interface V1Node {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1Node
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1Node
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1Node
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {V1NodeSpec}
     * @memberof V1Node
     */
    spec?: V1NodeSpec;
    /**
     * 
     * @type {V1NodeStatus}
     * @memberof V1Node
     */
    status?: V1NodeStatus;
}

/**
 * Check if a given object implements the V1Node interface.
 */
export function instanceOfV1Node(value: object): value is V1Node {
    return true;
}

export function V1NodeFromJSON(json: any): V1Node {
    return V1NodeFromJSONTyped(json, false);
}

export function V1NodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Node {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': json['spec'] == null ? undefined : V1NodeSpecFromJSON(json['spec']),
        'status': json['status'] == null ? undefined : V1NodeStatusFromJSON(json['status']),
    };
}

export function V1NodeToJSON(value?: V1Node | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'metadata': V1ObjectMetaToJSON(value['metadata']),
        'spec': V1NodeSpecToJSON(value['spec']),
        'status': V1NodeStatusToJSON(value['status']),
    };
}

