/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1DaemonEndpoint } from './V1DaemonEndpoint';
import {
    V1DaemonEndpointFromJSON,
    V1DaemonEndpointFromJSONTyped,
    V1DaemonEndpointToJSON,
} from './V1DaemonEndpoint';

/**
 * NodeDaemonEndpoints lists ports opened by daemons running on the Node.
 * @export
 * @interface V1NodeDaemonEndpoints
 */
export interface V1NodeDaemonEndpoints {
    /**
     * 
     * @type {V1DaemonEndpoint}
     * @memberof V1NodeDaemonEndpoints
     */
    kubeletEndpoint?: V1DaemonEndpoint;
}

/**
 * Check if a given object implements the V1NodeDaemonEndpoints interface.
 */
export function instanceOfV1NodeDaemonEndpoints(value: object): value is V1NodeDaemonEndpoints {
    return true;
}

export function V1NodeDaemonEndpointsFromJSON(json: any): V1NodeDaemonEndpoints {
    return V1NodeDaemonEndpointsFromJSONTyped(json, false);
}

export function V1NodeDaemonEndpointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1NodeDaemonEndpoints {
    if (json == null) {
        return json;
    }
    return {
        
        'kubeletEndpoint': json['kubeletEndpoint'] == null ? undefined : V1DaemonEndpointFromJSON(json['kubeletEndpoint']),
    };
}

export function V1NodeDaemonEndpointsToJSON(value?: V1NodeDaemonEndpoints | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'kubeletEndpoint': V1DaemonEndpointToJSON(value['kubeletEndpoint']),
    };
}

