/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PodFailurePolicyRule } from './V1PodFailurePolicyRule';
import {
    V1PodFailurePolicyRuleFromJSON,
    V1PodFailurePolicyRuleFromJSONTyped,
    V1PodFailurePolicyRuleToJSON,
} from './V1PodFailurePolicyRule';

/**
 * PodFailurePolicy describes how failed pods influence the backoffLimit.
 * @export
 * @interface V1PodFailurePolicy
 */
export interface V1PodFailurePolicy {
    /**
     * A list of pod failure policy rules. The rules are evaluated in order. Once a rule matches a Pod failure, the remaining of the rules are ignored. When no rule matches the Pod failure, the default handling applies - the counter of pod failures is incremented and it is checked against the backoffLimit. At most 20 elements are allowed.
     * @type {Array<V1PodFailurePolicyRule>}
     * @memberof V1PodFailurePolicy
     */
    rules: Array<V1PodFailurePolicyRule>;
}

/**
 * Check if a given object implements the V1PodFailurePolicy interface.
 */
export function instanceOfV1PodFailurePolicy(value: object): value is V1PodFailurePolicy {
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function V1PodFailurePolicyFromJSON(json: any): V1PodFailurePolicy {
    return V1PodFailurePolicyFromJSONTyped(json, false);
}

export function V1PodFailurePolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PodFailurePolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'rules': ((json['rules'] as Array<any>).map(V1PodFailurePolicyRuleFromJSON)),
    };
}

export function V1PodFailurePolicyToJSON(value?: V1PodFailurePolicy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rules': ((value['rules'] as Array<any>).map(V1PodFailurePolicyRuleToJSON)),
    };
}

