/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PodStatus } from './V1PodStatus';
import {
    V1PodStatusFromJSON,
    V1PodStatusFromJSONTyped,
    V1PodStatusToJSON,
} from './V1PodStatus';
import type { V1ObjectMeta } from './V1ObjectMeta';
import {
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
} from './V1ObjectMeta';
import type { V1PodSpec } from './V1PodSpec';
import {
    V1PodSpecFromJSON,
    V1PodSpecFromJSONTyped,
    V1PodSpecToJSON,
} from './V1PodSpec';

/**
 * Pod is a collection of containers that can run on a host. This resource is created by clients and scheduled onto hosts.
 * @export
 * @interface V1Pod
 */
export interface V1Pod {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1Pod
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1Pod
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1Pod
     */
    metadata?: V1ObjectMeta;
    /**
     * 
     * @type {V1PodSpec}
     * @memberof V1Pod
     */
    spec?: V1PodSpec;
    /**
     * 
     * @type {V1PodStatus}
     * @memberof V1Pod
     */
    status?: V1PodStatus;
}

/**
 * Check if a given object implements the V1Pod interface.
 */
export function instanceOfV1Pod(value: object): value is V1Pod {
    return true;
}

export function V1PodFromJSON(json: any): V1Pod {
    return V1PodFromJSONTyped(json, false);
}

export function V1PodFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Pod {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'metadata': json['metadata'] == null ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': json['spec'] == null ? undefined : V1PodSpecFromJSON(json['spec']),
        'status': json['status'] == null ? undefined : V1PodStatusFromJSON(json['status']),
    };
}

export function V1PodToJSON(value?: V1Pod | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'metadata': V1ObjectMetaToJSON(value['metadata']),
        'spec': V1PodSpecToJSON(value['spec']),
        'status': V1PodStatusToJSON(value['status']),
    };
}

