/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ExemptPriorityLevelConfiguration } from './V1ExemptPriorityLevelConfiguration';
import {
    V1ExemptPriorityLevelConfigurationFromJSON,
    V1ExemptPriorityLevelConfigurationFromJSONTyped,
    V1ExemptPriorityLevelConfigurationToJSON,
} from './V1ExemptPriorityLevelConfiguration';
import type { V1LimitedPriorityLevelConfiguration } from './V1LimitedPriorityLevelConfiguration';
import {
    V1LimitedPriorityLevelConfigurationFromJSON,
    V1LimitedPriorityLevelConfigurationFromJSONTyped,
    V1LimitedPriorityLevelConfigurationToJSON,
} from './V1LimitedPriorityLevelConfiguration';

/**
 * PriorityLevelConfigurationSpec specifies the configuration of a priority level.
 * @export
 * @interface V1PriorityLevelConfigurationSpec
 */
export interface V1PriorityLevelConfigurationSpec {
    /**
     * 
     * @type {V1ExemptPriorityLevelConfiguration}
     * @memberof V1PriorityLevelConfigurationSpec
     */
    exempt?: V1ExemptPriorityLevelConfiguration;
    /**
     * 
     * @type {V1LimitedPriorityLevelConfiguration}
     * @memberof V1PriorityLevelConfigurationSpec
     */
    limited?: V1LimitedPriorityLevelConfiguration;
    /**
     * `type` indicates whether this priority level is subject to limitation on request execution.  A value of `"Exempt"` means that requests of this priority level are not subject to a limit (and thus are never queued) and do not detract from the capacity made available to other priority levels.  A value of `"Limited"` means that (a) requests of this priority level _are_ subject to limits and (b) some of the server's limited capacity is made available exclusively to this priority level. Required.
     * @type {string}
     * @memberof V1PriorityLevelConfigurationSpec
     */
    type: string;
}

/**
 * Check if a given object implements the V1PriorityLevelConfigurationSpec interface.
 */
export function instanceOfV1PriorityLevelConfigurationSpec(value: object): value is V1PriorityLevelConfigurationSpec {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function V1PriorityLevelConfigurationSpecFromJSON(json: any): V1PriorityLevelConfigurationSpec {
    return V1PriorityLevelConfigurationSpecFromJSONTyped(json, false);
}

export function V1PriorityLevelConfigurationSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PriorityLevelConfigurationSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'exempt': json['exempt'] == null ? undefined : V1ExemptPriorityLevelConfigurationFromJSON(json['exempt']),
        'limited': json['limited'] == null ? undefined : V1LimitedPriorityLevelConfigurationFromJSON(json['limited']),
        'type': json['type'],
    };
}

export function V1PriorityLevelConfigurationSpecToJSON(value?: V1PriorityLevelConfigurationSpec | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exempt': V1ExemptPriorityLevelConfigurationToJSON(value['exempt']),
        'limited': V1LimitedPriorityLevelConfigurationToJSON(value['limited']),
        'type': value['type'],
    };
}

