/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: release-1.24
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType.
 * @export
 * @interface V1RollingUpdateStatefulSetStrategy
 */
export interface V1RollingUpdateStatefulSetStrategy {
    /**
     * The maximum number of pods that can be unavailable during the update. Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%). Absolute number is calculated from percentage by rounding up. This can not be 0. Defaults to 1. This field is alpha-level and is only honored by servers that enable the MaxUnavailableStatefulSet feature. The field applies to all pods in the range 0 to Replicas-1. That means if there is any unavailable pod in the range 0 to Replicas-1, it will be counted towards MaxUnavailable.
     * @type {object}
     * @memberof V1RollingUpdateStatefulSetStrategy
     */
    maxUnavailable?: object;
    /**
     * Partition indicates the ordinal at which the StatefulSet should be partitioned for updates. During a rolling update, all pods from ordinal Replicas-1 to Partition are updated. All pods from ordinal Partition-1 to 0 remain untouched. This is helpful in being able to do a canary based deployment. The default value is 0.
     * @type {number}
     * @memberof V1RollingUpdateStatefulSetStrategy
     */
    partition?: number;
}

export function V1RollingUpdateStatefulSetStrategyFromJSON(json: any): V1RollingUpdateStatefulSetStrategy {
    return V1RollingUpdateStatefulSetStrategyFromJSONTyped(json, false);
}

export function V1RollingUpdateStatefulSetStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1RollingUpdateStatefulSetStrategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maxUnavailable': !exists(json, 'maxUnavailable') ? undefined : json['maxUnavailable'],
        'partition': !exists(json, 'partition') ? undefined : json['partition'],
    };
}

export function V1RollingUpdateStatefulSetStrategyToJSON(value?: V1RollingUpdateStatefulSetStrategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maxUnavailable': value.maxUnavailable,
        'partition': value.partition,
    };
}


