/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SuccessPolicyRule } from './V1SuccessPolicyRule';
import {
    V1SuccessPolicyRuleFromJSON,
    V1SuccessPolicyRuleFromJSONTyped,
    V1SuccessPolicyRuleToJSON,
} from './V1SuccessPolicyRule';

/**
 * SuccessPolicy describes when a Job can be declared as succeeded based on the success of some indexes.
 * @export
 * @interface V1SuccessPolicy
 */
export interface V1SuccessPolicy {
    /**
     * rules represents the list of alternative rules for the declaring the Jobs as successful before `.status.succeeded >= .spec.completions`. Once any of the rules are met, the "SucceededCriteriaMet" condition is added, and the lingering pods are removed. The terminal state for such a Job has the "Complete" condition. Additionally, these rules are evaluated in order; Once the Job meets one of the rules, other rules are ignored. At most 20 elements are allowed.
     * @type {Array<V1SuccessPolicyRule>}
     * @memberof V1SuccessPolicy
     */
    rules: Array<V1SuccessPolicyRule>;
}

/**
 * Check if a given object implements the V1SuccessPolicy interface.
 */
export function instanceOfV1SuccessPolicy(value: object): value is V1SuccessPolicy {
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function V1SuccessPolicyFromJSON(json: any): V1SuccessPolicy {
    return V1SuccessPolicyFromJSONTyped(json, false);
}

export function V1SuccessPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SuccessPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'rules': ((json['rules'] as Array<any>).map(V1SuccessPolicyRuleFromJSON)),
    };
}

export function V1SuccessPolicyToJSON(value?: V1SuccessPolicy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rules': ((value['rules'] as Array<any>).map(V1SuccessPolicyRuleToJSON)),
    };
}

