/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * CrossVersionObjectReference contains enough information to let you identify the referred resource.
 * @export
 * @interface V2CrossVersionObjectReference
 */
export interface V2CrossVersionObjectReference {
    /**
     * apiVersion is the API version of the referent
     * @type {string}
     * @memberof V2CrossVersionObjectReference
     */
    apiVersion?: string;
    /**
     * kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V2CrossVersionObjectReference
     */
    kind: string;
    /**
     * name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
     * @type {string}
     * @memberof V2CrossVersionObjectReference
     */
    name: string;
}

/**
 * Check if a given object implements the V2CrossVersionObjectReference interface.
 */
export function instanceOfV2CrossVersionObjectReference(value: object): value is V2CrossVersionObjectReference {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function V2CrossVersionObjectReferenceFromJSON(json: any): V2CrossVersionObjectReference {
    return V2CrossVersionObjectReferenceFromJSONTyped(json, false);
}

export function V2CrossVersionObjectReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2CrossVersionObjectReference {
    if (json == null) {
        return json;
    }
    return {
        
        'apiVersion': json['apiVersion'] == null ? undefined : json['apiVersion'],
        'kind': json['kind'],
        'name': json['name'],
    };
}

export function V2CrossVersionObjectReferenceToJSON(value?: V2CrossVersionObjectReference | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiVersion': value['apiVersion'],
        'kind': value['kind'],
        'name': value['name'],
    };
}

