/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V2MetricIdentifier } from './V2MetricIdentifier';
import {
    V2MetricIdentifierFromJSON,
    V2MetricIdentifierFromJSONTyped,
    V2MetricIdentifierToJSON,
} from './V2MetricIdentifier';
import type { V2MetricValueStatus } from './V2MetricValueStatus';
import {
    V2MetricValueStatusFromJSON,
    V2MetricValueStatusFromJSONTyped,
    V2MetricValueStatusToJSON,
} from './V2MetricValueStatus';

/**
 * PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
 * @export
 * @interface V2PodsMetricStatus
 */
export interface V2PodsMetricStatus {
    /**
     * 
     * @type {V2MetricValueStatus}
     * @memberof V2PodsMetricStatus
     */
    current: V2MetricValueStatus;
    /**
     * 
     * @type {V2MetricIdentifier}
     * @memberof V2PodsMetricStatus
     */
    metric: V2MetricIdentifier;
}

/**
 * Check if a given object implements the V2PodsMetricStatus interface.
 */
export function instanceOfV2PodsMetricStatus(value: object): value is V2PodsMetricStatus {
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('metric' in value) || value['metric'] === undefined) return false;
    return true;
}

export function V2PodsMetricStatusFromJSON(json: any): V2PodsMetricStatus {
    return V2PodsMetricStatusFromJSONTyped(json, false);
}

export function V2PodsMetricStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2PodsMetricStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'current': V2MetricValueStatusFromJSON(json['current']),
        'metric': V2MetricIdentifierFromJSON(json['metric']),
    };
}

export function V2PodsMetricStatusToJSON(value?: V2PodsMetricStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'current': V2MetricValueStatusToJSON(value['current']),
        'metric': V2MetricIdentifierToJSON(value['metric']),
    };
}

