name: flow
on: push
jobs:
  flow:
    runs-on: ubuntu-latest
    container: alpine:3.20
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: apk add npm
      - name: build
        # prepare script builds
        run: npm ci
      - name: publish
        if: ${{ github.ref_type == 'tag' }}
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
