name: flow
on: push
jobs:
  flow:
    runs-on: ubuntu-latest
    container: alpine:3.20
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: |
          apk add npm
          npm config set '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'
      - name: build
        # prepare script builds
        run: npm ci
      - name: publish
        if: ${{ github.ref_type == 'tag' }}
        # too much files, npm print file sizes on notice level
        run: npm --loglevel warn publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
